### ISSUE TITLE
Route [filament.auth.login] not defined

### ISSUE THREAD

**Issue by naingwin** [solutionforest/filament-access-management#10]
Route [filament.auth.login] not defined after upgrade filament v2 to 3 and upgrade filament-access-management v1 to 2

**Comment by lam0819** [comment]
do you add ?
->plugin(FilamentAccessManagementPanel::make());

**Comment by szerambo** [comment]
I'm now having the same issue. What should I do to resolve this?

**Comment by cklei-carly** [comment]
The  [installation instructions](https://github.com/solutionforest/filament-access-management?tab=readme-ov-file#installation) have been updated, please reference this and re-try the installation.

(If you're using Filament v3, please upgrade the "solution-forest/filament-access-management" package to "^2.2.0"

The key points are:

1. Clear your caches
2. Ensure you have the Filament panel provider set up
3. Add the Filament Access Management plugin  (SolutionForest\FilamentAccessManagement\FilamentAccessManagementPanel) to your panel provider
4. Upgrade the package version if you're using Filament v3
5. Refresh your browser cache
