### ISSUE TITLE
Not able to edit the menu. On editing a menu item showing BadMethodCallException in the modal

### ISSUE THREAD

**Issue by mthabsheer** [solutionforest/filament-access-management#14]
While trying to edit the menu item getting below error:

`Method SolutionForest\FilamentTree\Actions\EditAction::shouldOpenModal does not exist.`

![error](https://github.com/solutionforest/filament-access-management/assets/30547357/9fb60c9d-3a69-4c99-8aef-50b05be01f49)

The error dissappears when I commented out the selected lines and uncomment the existing commented lines in the file located in the below path.

**vendor\solution-forest\filament-tree\src\Concern\HasActions.php**

I kept the below lines commented itself

`// if ($action->shouldOpenModal()) {
        //     return false;
        // }`

Please see the code snippet below

![error2](https://github.com/solutionforest/filament-access-management/assets/30547357/fbe3fff9-7480-4587-af18-81293f9f39ce)

I am using this plugin for first time. Please guide if there is any thing to be done to make this function definition available in the code.

**Comment by cklei-carly** [comment]
Please upgrade to version 2.2.0 or higher to support more method for tree actions
