### ISSUE TITLE
Missing required parameter for [Route: filament.admin.pages.dashboard] [URI: admin/{tenant}] [Missing parameter: tenant].

### ISSUE THREAD

**Issue by zxstudio-llc** [solutionforest/filament-access-management#15]
Hello dear developer, try the installation with "php artisan filament-access-management:install
" but it returns this error, I am working with multitenancy, any suggestions to resolve this error

php artisan filament-access-management:install

Publishing config...
Publishing migrations...
filament-access-management has been installed!

   INFO  Running migrations.

  2024_05_14_164524_create_filament_admin_tables ..... 458.20ms DONE

   INFO  Seeding database.

   INFO  Seeding database.

   Illuminate\Routing\Exceptions\UrlGenerationException

  Missing required parameter for [Route: filament.admin.pages.dashboard] [URI: admin/{tenant}] [Missing parameter: tenant].

  at vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:35
     31▕         }
     32▕
     33▕         $message .= '.';
     34▕
  ➜  35▕         return new static($message);
     36▕     }
     37▕ }
     38▕

      +8 vendor frames

  9   [internal]:0
      SolutionForest\FilamentAccessManagement\Database\Seeders\NavigationSeeder::SolutionForest\FilamentAccessManagement\Database\Seeders\{closure}("Filament\Pages\Dashboard")
      +38 vendor frames

  48  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))

**Comment by cklei-carly** [comment]
Please upgrade to v2.2.0 or higher to support multitenancy
