### ISSUE TITLE
composer require solution-forest/filament-access-management DON'T install same files (like FilamentUserHelpers)

### ISSUE THREAD

**Issue by APMU** [solutionforest/filament-access-management#5]
Hi,

After run composer require solution-forest/filament-access-management some files do not find on vendor folder.

On Src\Concerns, only "FilamentUser.php", but dont have "FilamentUserHelpers.php"

How to fix?

**Comment by justgkp** [comment]
same issue for me as well.
Trait "SolutionForest\FilamentAccessManagement\Concerns\FilamentUserHelpers" not found

**Comment by lam0819** [comment]
sorry the package was not released. please update the latest library.
