### ISSUE TITLE
Route [filament.auth.login] not defined, after enable filament-access-management on FilamentPHP 3.0.

### ISSUE THREAD

**Issue by APMU** [solutionforest/filament-access-management#8]
Hi Guys,

On fresh install of FilamentPHP 3.0 with filament-access-management, have a error after route exception:

"Route [filament.auth.login] not defined".

When disable filament-access-management, the error finishes. Someone have this issue? Ho to fix?

Thanks,

Alex

**Comment by APMU** [comment]
Fixed.

**Comment by naingwin** [comment]
I'm facing with this issue, may I know how to fix ?

**Comment by naingwin** [comment]
@APMU can you please help me to fix this please?
