### ISSUE TITLE
Customize the UserResource

### ISSUE THREAD

**Issue by naingwin** [solutionforest/filament-access-management#9]
I want to add the getEloquentQuery() to UserResource and add more columns and fields to ListPage and CreatePage. I already tested with new UserResource and not working.

**Comment by cklei-carly** [comment]
Please add your resource on `config/filament-access-management.php` file.

```php
// config/filament-access-management.php
return [
  'filament' => [
      'resources' => [
              \App\Filament\Resources\UserResource::class,
              Resources\RoleResource::class,
              Resources\PermissionResource::class,
      ],
  ],
];
```
